### ISSUE TITLE
manifest version 3 support coming?

### ISSUE THREAD

**Issue by gpscruise** [dmillz/Comic-Text#5]
i cant load manifest 2.

What can I do instead??  

thanks!

**Comment by dmillz** [comment]
Hey, thanks for opening this as an issue!

I haven't cut a release for Comic Text since 2018, so it's been a minute 😅. Changes to the web store since then will likely complicate matters, but the upgrade to manifest v3 is straightforward enough. 

I'll see what I can do 😁

**Comment by dmillz** [comment]
Version 3.0.0 of Comic Text has now been published to the Chrome Web Store, which includes support for manifest v3. Please let me know if you encounter any issues.
